<?php
/**
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

namespace app\assets;

use app\common\services\UrlService;
use yii\web\AssetBundle;

class WebAsset extends AssetBundle
{
    public $basePath = '@webroot';
    public $baseUrl = '@web';

    public function registerAssetFiles($view)
    {
        // 版本号是一个常量，加载js，css是有业务的
        $release_version = RELEASE_VERSION ?? time();

        $this->css = [
            'css/web/bootstrap.min.css',
            'font-awesome/css/font-awesome.css',
            'css/web/style.css?ver=' . $release_version,
        ];

        $this->js = [
            UrlService::buildWwwUrl("/plugins/jquery-2.1.1.js"),
            UrlService::buildWwwUrl("/js/web/bootstrap.min.js"),
            UrlService::buildWwwUrl("/plugins/layer/layer.js"),
            UrlService::buildWwwUrl("/js/web/common.js", ['ver' => $release_version]),
        ];
        parent::registerAssetFiles($view); // TODO: Change the autogenerated stub
    }
}
